# This is a basic workflow to help you get started with Actions

name: Builds apk for Slack

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-20.04
  
    steps:
        - uses: actions/checkout@v2
        - name: set up JDK 1.8
          uses: actions/setup-java@v1.3.0
          with:
            java-version: 1.8

        - name: Grant Permission to Execute
          run: chmod +x gradlew

        - name: Build debug APK
          run: bash ./gradlew assembleDebug --stacktrace

      # Upload APK to Github Artifacts
        - name: Upload APK to Github Artifacts
          uses: actions/upload-artifact@v2
          with:
            name: app
            path: app/build/outputs/apk/debug/app-debug.apk
